### ISSUE TITLE
FPU in interrupt

### ISSUE THREAD

**Issue by martinribelotta** [hydrausb3/riscv-none-elf-gcc-xpack#5]
# FPU save context on `WCH-Interrupt-fast`

I'm working with this toolchain for ch32v307 MCU enabling FPU subsystem.

The section 3.4 of [QingKeV4 Microprocessor Manual](https://www.wch-ic.com/downloads/QingKeV4_Processor_Manual_PDF.html) saids that the FPU registers need to saved normally even if the function is marked as `WCH-Interrupt-fast`

![image](https://github.com/hydrausb3/riscv-none-elf-gcc-xpack/assets/692175/47a0ac51-1191-42b1-a80b-f5489627e8de)

I try to build same code with binary provided toolchains from WCH and with this toolchain and the result differ great:

The code in question is:

```c
void ADC1_2_IRQHandler(void) __attribute__((interrupt("WCH-Interrupt-fast")));

void ADC1_2_IRQHandler()
{
    u16 ADC_val;

    if(ADC_GetITStatus(ADC1, ADC_IT_JEOC))
    {
        printf("ADC Extline trigger conversion...\r\n");
        ADC_val = ADC_GetInjectedConversionValue(ADC1, ADC_InjectedChannel_1);

        printf("JADC %04d\r\n", Get_ConversionVal(ADC_val));
    }

    ADC_ClearITPendingBit(ADC1, ADC_IT_JEOC);
}
```
From [main on EVT/EXAM/ADC/TIM_Trigger @ openwch/ch32v307](https://github.com/openwch/ch32v307/blob/main/EVT/EXAM/ADC/TIM_Trigger/User/main.c#L166)

And the disassembled result is, for riscv-none-embed from WCH:

```
<ADC1_2_IRQHandler>:
     addi	sp,sp,-80
     fsw	ft0,76(sp)
     fsw	ft1,72(sp)
     fsw	ft2,68(sp)
     fsw	ft3,64(sp)
     fsw	ft4,60(sp)
     fsw	ft5,56(sp)
     fsw	ft6,52(sp)
     fsw	ft7,48(sp)
     fsw	fa0,44(sp)
     fsw	fa1,40(sp)
     fsw	fa2,36(sp)
     fsw	fa3,32(sp)
     fsw	fa4,28(sp)
     fsw	fa5,24(sp)
     fsw	fa6,20(sp)
     fsw	fa7,16(sp)
     fsw	ft8,12(sp)
     fsw	ft9,8(sp)
     fsw	ft10,4(sp)
     fsw	ft11,0(sp)
     li	a1,1152
     lui	a0,0x40012
     addi	a0,a0,1024 # 40012400 <_eusrstack+0x2000a400>
     jal	<ADC_GetITStatus>
     bnez	a0, <ADC1_2_IRQHandler+0x76>
     li	a1,1152
     lui	a0,0x40012
     addi	a0,a0,1024 # 40012400 <_eusrstack+0x2000a400>
     jal	<ADC_ClearITPendingBit>
     flw	ft0,76(sp)
     flw	ft1,72(sp)
     flw	ft2,68(sp)
     flw	ft3,64(sp)
     flw	ft4,60(sp)
     flw	ft5,56(sp)
     flw	ft6,52(sp)
     flw	ft7,48(sp)
     flw	fa0,44(sp)
     flw	fa1,40(sp)
     flw	fa2,36(sp)
     flw	fa3,32(sp)
     flw	fa4,28(sp)
     flw	fa5,24(sp)
     flw	fa6,20(sp)
     flw	fa7,16(sp)
     flw	ft8,12(sp)
     flw	ft9,8(sp)
     flw	ft10,4(sp)
     flw	ft11,0(sp)
     addi	sp,sp,80
     mret
     lui	a0,0xd
     addi	a0,a0,968 # d3c8 <_read+0xc>
     jal	ra,16c8 <puts>
     li	a1,20
     lui	a0,0x40012
     addi	a0,a0,1024 # 40012400 <_eusrstack+0x2000a400>
     jal	<ADC_GetInjectedConversionValue>
     slli	a0,a0,0x10
     srai	a0,a0,0x10
     jal	488 <Get_ConversionVal>
     mv	a1,a0
     lui	a0,0xd
     addi	a0,a0,1004 # d3ec <_read+0x30>
     jal	ra, <printf>
     j	        <ADC1_2_IRQHandler+0x3a>
```

And for riscv-none-elf provided in this repository:

```
<ADC1_2_IRQHandler>:
     li	a1,1152
     lui	a0,0x40012
     addi	a0,a0,1024 # 40012400 <_eusrstack+0x2000a400>
     jal	<ADC_GetITStatus>
     bnez	a0, <ADC1_2_IRQHandler+0x22>
     li	a1,1152
     lui	a0,0x40012
     addi	a0,a0,1024 # 40012400 <_eusrstack+0x2000a400>
     jal	<ADC_ClearITPendingBit>
     mret
     lui	a0,0xb
     addi	a0,a0,320 # b140 <_exit+0x2a>
     jal	ra,1650 <puts>
     li	a1,20
     lui	a0,0x40012
     addi	a0,a0,1024 # 40012400 <_eusrstack+0x2000a400>
     jal	<ADC_GetInjectedConversionValue>
     slli	a0,a0,0x10
     srai	a0,a0,0x10
     jal	488 <Get_ConversionVal>
     mv	a1,a0
     lui	a0,0xb
     addi	a0,a0,356 # b164 <_exit+0x4e>
     jal	ra, <printf>
     j	        <ADC1_2_IRQHandler+0x10>
```
(this is edited removing address and binary codes but in short, the code is untouched)

The functionallity of the code is same but the WCH toolchain save the FPU registers correctly, instead the new gcc-12 riscv-none-elf relies on hardware-push to stack FPU registers correctly

You can see side by side the diference in this rutines
![image](https://github.com/hydrausb3/riscv-none-elf-gcc-xpack/assets/692175/dff0db75-2fcc-48ac-82bf-819be2abdf76)

This issue make unusable the FPU in chips with this feature (not a problem for CH56x series)

If the FPU support in this toolchain is not a problem, you can orient me to make the corresponding changes to this patch?

**Comment by jnk0le** [comment]
BTW 
- llvm with `-mllvm -enable-ipra` gets rid of those pushes when unnecessary
- situation with this attribute is already getting ridiculous. With [prestacked annotation](https://github.com/jnk0le/riscv-total-embedded/blob/master/riscv-total-embedded.adoc#151-prestacked-annotation) we wouldn't need to care about another proprietary stacking attribute if they ever add FP stacking

**Comment by martinribelotta** [comment]
> BTW
> 
> * llvm with `-mllvm -enable-ipra` gets rid of those pushes when unnecessary
Register allocation in gcc is very limited. I need to make my ISRs to call only inlinable functions (and resoluble in compile time at the same build unit)

Maybe if LLVM+Clang have ipra, the solution will be make a risc-v toolchain based on it...

> * situation with this attribute is already getting ridiculus. with [prestacked annotation](https://github.com/jnk0le/riscv-total-embedded/blob/master/riscv-total-embedded.adoc#151-prestacked-annotation) we wouldn't need to care about another proprietary stacking attribute if they ever add FP stacking

This sound like a great solution... I work in deeply embedded systems and the FPGA/ASIC implementations is a nigthmare of fragmentation in ISR handling
What about implementation roadmap in official gcc or some dedicated branch?

**Comment by jnk0le** [comment]
about the patch, someone has already done it

https://github.com/mengfanyuc/riscv-none-elf-gcc-xpack/commit/59ee16df7b6bf5ebbfa881a79f61dcf67eadb8e9

**Comment by jnk0le** [comment]
>What about implementation roadmap in official gcc or some dedicated branch?

I should finally send rfc somewhere...

**Comment by martinribelotta** [comment]
> about the patch, someone has already done it
> 
> [mengfanyuc@59ee16d](https://github.com/mengfanyuc/riscv-none-elf-gcc-xpack/commit/59ee16df7b6bf5ebbfa881a79f61dcf67eadb8e9)

Looks nice! I can build a temorary toolchain from your branch

**Comment by martinribelotta** [comment]
I close this issue because this toolchain is only for ch56x that not contains FPU and is not required here
